version: '3'
services:
    sender:
        build:
            context: tcpdumper
        entrypoint: /bin/bash
#        container_name: sender
        stdin_open: true
        tty: true
        cap_add:
            - NET_ADMIN
    arpspoofer:
        build: 
            context: arpspoofer
        entrypoint: /bin/bash
#        container_name: arpspoofer
        stdin_open: true
        tty: true

    reciver:
        build:
            context: tcpdumper
        entrypoint: /bin/bash
        stdin_open: true
        tty: true
        cap_add:
            - NET_ADMIN
#        container_name: reciver
